feat: Support the configuration of slaves to use only dc sync1
robert-burger/libethercat pull request #21
Opened 2024-09-03 13:23 UTC by marcfir

Our problems with #15 come from a wrong DC configuration.
TwinCAT only uses the SYNC1 signal. If we use the same configuration, the slave can go to OP.

I don't know how to read this from the ESI, but it works.
```xml
<Dc>
	<OpMode>
		<Name>DcSync500us</Name>
		<Desc>DC-Synchron (Sync0Shift 500us)</Desc>
		<AssignActivate>#x0500</AssignActivate>
		<CycleTimeSync0 Factor="1">0</CycleTimeSync0>
		<ShiftTimeSync0>500000</ShiftTimeSync0>
	</OpMode>
	<OpMode>
		<Name>DcSync250us</Name>
		<Desc>DC-Synchron (Sync0Shift 250us)</Desc>
		<AssignActivate>#x0500</AssignActivate>
		<CycleTimeSync0 Factor="1">0</CycleTimeSync0>
		<ShiftTimeSync0>250000</ShiftTimeSync0>
	</OpMode>
	<OpMode>
		<Name>DcSync1000us</Name>
		<Desc>DC-Synchron (Sync0Shift 1000us)</Desc>
		<AssignActivate>#x0500</AssignActivate>
		<CycleTimeSync0 Factor="1">0</CycleTimeSync0>
		<ShiftTimeSync0>1000000</ShiftTimeSync0>
	</OpMode>
	<OpMode>
		<Name>FreeRun</Name>
		<Desc>Free Run (no synchronization)</Desc>
		<AssignActivate>#x0000</AssignActivate>
	</OpMode>
</Dc>
```

2024-09-10 04:48 UTC, robert-burger commented
ok it understand but did not see that configuration so far.

the "AssignActivate" is simply the content written to register 0x981 (activation register, byte swapped in XML). 

Bit 0 : sync activation
Bit 1 : sync0 generation
Bit 2 : sync1 generation

I totally have no idea why they preferred sync 1 generation over sync 0, but obviously they did. Regarding your last comment, can you make the changes to pass the register content directly in `ec_slave_set_dc_config`? maybe also rename `slv.dc.type` to `slv.dc.activation_reg`?

2024-09-10 04:49 UTC, robert-burger requested changes
write activation reg directly

2024-09-13 18:34 UTC, marcfir commented
Hello Robert. I have added the changes. Does that fit?

2024-09-14 06:44 UTC, robert-burger approved these changes
Lgtm. Very nice, thanks.

2024-09-14 06:45 UTC, merged