Enable custom rtc clock source
robert-burger/libethercat pull request #25
Opened 2024-09-13 19:24 UTC by marcfir

Solves #23 

The question for me is whether the following line also needs to be adapted to the custom CLOCK_SOURCE.
https://github.com/robert-burger/libethercat/blob/9108db144f028f763203957c595d9b39bc04505e/src/dc.c#L354

The packet latency in
https://github.com/robert-burger/libethercat/blob/9108db144f028f763203957c595d9b39bc04505e/src/dc.c#L100-L108
also uses `osal_timer_gettime_nsec()`. In libosal for POSIX, CLOCK_REALTIME is currently used, which I think is not optimal, because it can be changed by NTP ([see here](https://man7.org/linux/man-pages/man3/clock_gettime.3.html)). So, at least for Linux CLOCK_MONOTONIC is better.

For measuring packet latency it doesn't matter which time reference is used, but for DC sync it is important if you want to synchronize the master rtc to an external clock, e.g. via PTP. In this case, you would prefer CLOCK_TAI.

2024-09-14 06:41 UTC, robert-burger commented
Hi Marc,

i know that CLOCK_REALTIME is affected by NTP (i think our realtime system do not use NTP) so switching to a different clock source is a good option here.

But despite modifying/hacking this into libethercat wouldn't it be better to make it configurable in libosal to support CLOCK_MONOTIC(_RAW) and CLOCK_TAI? Then we do not need to take care about where a different clock source might be used here.

Cheers 
Robert

2024-09-17 10:34 UTC, marcfir commented
Hi Robert,
Making the libosal configurable sounds good. I can make a suggestion. 
Just a question about the `ec_send_distributed_clocks`. When using SO_TXTIME, you use the `send()` call before the actual send time to queue the frames in the ethernet adapter with a txtime. The adapter will then send the frames at the specified time. So I think `ec_send_distributed_clocks` should use the specified txtime, right?

2024-10-11 08:54 UTC, robert-burger commented
is this still necessary although we changed clock source in libosal?

2025-02-10 07:03 UTC, robert-wm requested changes
i think we could add this as it might be useful to provide times from other clocks source.

2025-02-10 07:03 UTC, robert-wm commented on src/ec.c
> +    return ec_send_distributed_clocks_sync_intern(pec,0);
wouldn't it be better to pass `osal_timer_gettime_nsec()` instead of `0`? then we could skip the check of line 1885..

2025-02-10 07:03 UTC, robert-wm commented on src/ec.c
> +int ec_send_distributed_clocks_sync_intern(ec_t *pec, osal_uint64_t act_rtc_time) {
could you do a forward declaration of the `..._intern` function as static at the beginning of the file?

2025-02-10 15:25 UTC, marcfir commented on src/ec.c
> +    return ec_send_distributed_clocks_sync_intern(pec,0);
Yes, this makes sense

2025-02-10 15:27 UTC, marcfir commented on src/ec.c
> +int ec_send_distributed_clocks_sync_intern(ec_t *pec, osal_uint64_t act_rtc_time) {
Of course I can. What is the reason for this? Just out of interest.

2025-02-10 15:52 UTC, marcfir commented
Rebased and ready

2025-02-10 17:56 UTC, merged